# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Moscow_Places' do
use_frameworks!

pod 'Kingfisher'

  target 'Moscow_PlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Moscow_PlacesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
